import { FormUI } from '@ngkits/tailwindcss';

export const formUi: FormUI = {
  groups: [
    {
      name: 'Group 1',
      fields: [
        {
          name: 'TextField',
          type: 0,
          hidden: false,
          mandatory: true,
          row: 1,
          column: 1,
        },
        {
          name: 'RadioButton',
          type: 1,
          hidden: false,
          mandatory: false,
          row: 2,
          column: 1,
        },
        {
          name: 'RadioButtonGroup',
          type: 2,
          hidden: false,
          mandatory: true,
          row: 3,
          column: 1,
          items: ['Option 1', 'Option 2', 'Option 3'],
        },
        {
          name: 'CheckBox',
          type: 3,
          hidden: false,
          mandatory: false,
          row: 4,
          column: 1,
        },
        {
          name: 'CheckBoxGroup',
          type: 4,
          hidden: false,
          mandatory: true,
          row: 5,
          column: 1,
          items: ['Option 1', 'Option 2', 'Option 3'],
        },
        {
          name: 'DropDown',
          type: 5,
          hidden: false,
          mandatory: true,
          row: 6,
          column: 1,
          items: ['Option 1', 'Option 2', 'Option 3'],
        },
        {
          name: 'ComboBox',
          type: 6,
          hidden: false,
          mandatory: false,
          row: 7,
          column: 1,
        },
        {
          name: 'AutoComplete',
          type: 7,
          hidden: true,
          mandatory: true,
          row: 8,
          column: 1,
        },
        {
          name: 'Grid',
          type: 8,
          hidden: false,
          mandatory: false,
          row: 9,
          column: 1,
        },
        {
          name: 'LookUp',
          type: 9,
          hidden: true,
          mandatory: true,
          row: 10,
          column: 1,
        },
      ],
    },
  ],
};
